device: auto
out_dir: results
case: bridge
seed: 76
num_workers: 0
print: both
metric_best: mse

### debug settings
neptune_agg: false
neptune_each_run: false
tensorboard_each_run: true
draw_learned_graph: false

### dataset settings
dataset:
  dir: datasets/bridge
  train_file: train.csv
  test_file: test.csv
  scaler_type: cminmax
  normalize: true
  window_size: 30
  stride: 5
  y_var: ['TrainLoad']
  include_lowf: true
  include_highf: true
  include_exo: true
  aug_lowf_diff: false
  only_lowf_diff: true

task:
  type: bridge
  train_type: mapping
  level: graph

### default model paramters
model:
  output_dim: 1
  dropout: 0.2
  activation: silu
  norm_func: batch
  type: gcnn
  gcnn:
    gated: true
    concat: true
    context_dim: 10
    enc_type: emb
    channel_sizes: [50, 50, 1]
    dilations: [1, 2]
    kernel_sizes: [3, 5]
    hidden_dim: 50
    n_head_layers: 3


### training paramters
train:
  shuffle: true
  ckpt_period: 2
  draw_period: 1
  auto_resume: true
  epoch_resume: -1
  ckpt_clean: true
  batch_size: 512
  early_stop_patience: 20
  early_stop_min: 50
  
### optimizer paramters
optim:
  warmup: true
  warmup_iters: 200
  warmup_initial_lr: 1e-4
  base_lr: 5e-3
  max_epochs: 150
  scheduler: plateau
  patience: 5
  factor: 0.9
  criterion: l2
